<!-- ADDRESS -->

      <div class="desktop">
         <div class="paragraphs-address">
            <p>
               <a target="_blank" href="mailto:onedevs.digital.services@gmail.com">onedevs.digital.services@gmail.com</a> &nbsp;&nbsp; | &nbsp;&nbsp;
               <a target="_blank" href="https://www.google.com/maps/place/OneDevs+Digital+Services/@37.8796277,-4.7641025,15z/data=!4m5!3m4!1s0x0:0xd2ab458934f9329f!8m2!3d37.8796277!4d-4.7641025">Córdoba City - 14010 - Spain</a> &nbsp;&nbsp; | &nbsp;&nbsp;
               <a target="_blank" href="tel:+34633823008">+34 633 82 30 08</a>
            </p>
         </div>
      </div>

      <div class="mobile">
         <div class="paragraphs-address">
            <p>
               <a target="_blank" href="mailto:onedevs.digital.services@gmail.com">onedevs.digital.services@gmail.com</a><br />
               <a target="_blank" href="https://www.google.com/maps/place/OneDevs+Digital+Services/@37.8796277,-4.7641025,15z/data=!4m5!3m4!1s0x0:0xd2ab458934f9329f!8m2!3d37.8796277!4d-4.7641025">Córdoba City - 14010 - Spain</a><br />
               <a target="_blank" href="tel:+34633823008">+34 633 82 30 08</a><br />
            </p>
         </div>
      </div>
