<!-- COLLABORATORS -->

      <div class="desktop">
         <div class="paragraphs">
            <div class="title">
               Talento OneDevs
            </div>            
            <div class="collaborator">
               <table class="collaborator">
                  <tbody>
                     <tr>
                        <td class="image">
                           <img src="/images/collaborators/richi.png" width="200" height="200" alt="Richi" />
                        </td>
                        <td class="content">
                           <span class="name-and-position">Ricardo Ruiz Martínez ( PHP Backend Developer )</span><br />
                           <i>"Buscamos ofrecer un amplio abanico de posibilidades digitales a quienes nos elijan como su proveedor de servicios digitales".</i><br />
                           <br />
                           <a target="_blank" href="mailto:richiruizmartinez@gmail.com">richiruizmartinez@gmail.com</a><br />
                           <a target="_blank" href="tel:+34744653072">+34 744 653 072</a><br />
                        </td>
                     </tr>
                     <tr>
                        <td class="image">
                           <img src="/images/collaborators/conchi.png" width="200" height="200" alt="Conchi" />
                        </td>
                        <td class="content">
                           <span class="name-and-position">Concepción Martínez Fernández ( Sales Manager )</span><br />
                           <i>"OneDevs permite desarrollar mis capacidades como Sales Manager".</i><br />
                           <br />
                           <a target="_blank" href="mailto:concepcion.mf.22f@gmail.com">concepcion.mf.22f@gmail.com</a><br />
                           <a target="_blank" href="tel:+34622134851">+34 622 13 48 51</a><br />
                        </td>
                     </tr>
                  </tbody>
               </table>
            </div>
         </div>
      </div>

      <div class="mobile">
         <div class="paragraphs">
            <div class="title">
               Talento OneDevs
            </div>            
            <div class="collaborators">
               <div class="collaborator">
                  <div class="image">
                     <img src="/images/collaborators/richi.png" width="200" height="200" alt="Richi" />
                  </div>
                  <div class="content">
                     <span class="name-and-position">Ricardo Ruiz Martínez ( CEO & Desarrollador Fullstack )</span><br />
                     <i>"Buscamos ofrecer un amplio abanico de posibilidades digitales a quienes nos elijan como su proveedor de servicios digitales".</i><br />
                     <br />
                     <a target="_blank" href="mailto:richiruizmartinez@gmail.com">richiruizmartinez@gmail.com</a><br />
                     <a target="_blank" href="tel:+34744653072">+34 744 653 072</a><br />
                  </div>
               </div>
               <div class="collaborator">
                  <div class="image">
                     <img src="/images/collaborators/conchi.png" width="200" height="200" alt="Conchi" />
                  </div>
                  <div class="content">
                     <span class="name-and-position">Concepción Martínez Fernández ( Sales Manager )</span><br />
                     <i>"OneDevs permite desarrollar mis capacidades como Sales Manager".</i><br />
                     <br />
                     <a target="_blank" href="mailto:concepcion.mf.22f@gmail.com">concepcion.mf.22f@gmail.com</a><br />
                     <a target="_blank" href="tel:+34622134851">+34 622 13 48 51</a><br />
                  </div>
               </div>
            </div>
         </div>
      </div>

