<!-- CONTACT -->

      <div class="paragraphs">
         <div class="title">
            ¿Quieres decirnos algo?
         </div>            
         <p>
            <br />
            <b>OneDevs Digital Services</b><br />
            <br />
            <a target="_blank" href="mailto:onedevs.digital.services@gmail.com">📬 onedevs.digital.services@gmail.com</a><br />
            <a target="_blank" href="tel:+34633823008"><img src="/images/icons/phone-ring-flat/32x32.png" alt="Phone" width="32" height="32" align="absmiddle" /> +34 633 823 008</a><br />
         </p>
      </div>

