<!-- CONTACT -->

      <div class="paragraphs">
         <div class="title">
            Contacta con nosotros
         </div>            
         <p>
            <br />
            <b>OneDevs Digital Services</b><br />
            <br />
            <a target="_blank" href="mailto:onedevs.digital.services@gmail.com">onedevs.digital.services@gmail.com</a><br />
            <a target="_blank" href="tel:+34633823008">+34 633 82 30 08</a><br />
         </p>
      </div>

