<!-- PEOPLE -->

      <?php

         $richi_index = \rand(0, 3);

      ?>

      <div class="desktop">
         <div class="paragraphs">
            <div class="title">
               Somos OneDevs
            </div>            
            <div class="collaborator">
               <table class="collaborator">
                  <tbody>
                     <tr>
                        <td class="image">
                           <img src="/images/people/richi-<?= $richi_index ?>.png" width="200" height="200" alt="Richi" />
                        </td>
                        <td class="content">
                           <span class="name-and-position">Ricardo Ruiz Martínez - CEO & Desarrollador Backend PHP</span><br />
                           <i>"Emprendemos la aventura OneDevs para poner nuestra actitud y capacidades al servicio de quienes quieran confiar en nosotros. Para nosotros, las necesidades digitales y tecnológicas de nuestros clientes son nuestras necesidades. Yo particularmente tengo más de doce años de experiencia como desarrollador backend PHP para potentes consultoras en Madrid y Grandes Firmas."</i><br />
                           <br />
                           <a target="_blank" href="mailto:richiruizmartinez@gmail.com">richiruizmartinez@gmail.com</a><br />
                           <a target="_blank" href="tel:+34744653072">+34 744 653 072</a><br />
                        </td>
                     </tr>
                     <tr>
                        <td class="image">
                           <img src="/images/people/conchi.png" width="200" height="200" alt="Conchi" />
                        </td>
                        <td class="content">
                           <span class="name-and-position">Concepción Martínez Fernández - Sales Manager</span><br />
                           <i>"Trabajo para OneDevs porque he trabajado en muchas empresas y la que más me ha gustado es OneDevs. Es innovadora."</i><br />
                           <br />
                           <a target="_blank" href="mailto:concepcion.mf.22f@gmail.com">concepcion.mf.22f@gmail.com</a><br />
                           <a target="_blank" href="tel:+34622134851">+34 622 13 48 51</a><br />
                        </td>
                     </tr>
                  </tbody>
               </table>
            </div>
         </div>
      </div>

      <div class="mobile">
         <div class="paragraphs">
            <div class="title">
               Somos OneDevs
            </div>            
            <div class="collaborators">
               <div class="collaborator">
                  <div class="image">
                     <img src="/images/people/richi-<?= $richi_index ?>.png" width="200" height="200" alt="Richi" />
                  </div>
                  <div class="content">
                     <span class="name-and-position">Ricardo Ruiz Martínez - CEO & Desarrollador Backend PHP</span><br />
                     <i>"Emprendemos la aventura OneDevs para poner nuestra actitud y capacidades al servicio de quienes quieran confiar en nosotros. Para nosotros, las necesidades digitales y tecnológicas de nuestros clientes son nuestras necesidades. Yo particularmente tengo más de doce años de experiencia como desarrollador backend PHP para potentes consultoras en Madrid y Grandes Firmas."</i><br />
                     <br />
                     <a target="_blank" href="mailto:richiruizmartinez@gmail.com">richiruizmartinez@gmail.com</a><br />
                     <a target="_blank" href="tel:+34744653072">+34 744 653 072</a><br />
                  </div>
               </div>
               <div class="collaborator">
                  <div class="image">
                     <img src="/images/people/conchi.png" width="200" height="200" alt="Conchi" />
                  </div>
                  <div class="content">
                     <span class="name-and-position">Concepción Martínez Fernández - Sales Manager</span><br />
                     <i>"Trabajo para OneDevs porque he trabajado en muchas empresas y la que más me ha gustado es OneDevs. Es innovadora."</i><br />
                     <br />
                     <a target="_blank" href="mailto:concepcion.mf.22f@gmail.com">concepcion.mf.22f@gmail.com</a><br />
                     <a target="_blank" href="tel:+34622134851">+34 622 13 48 51</a><br />
                  </div>
               </div>
            </div>
         </div>
      </div>

