<!-- TECH STACK -->

      <div class="paragraphs">
         <ul>
            <li>ASM 80x86</li>
            <li>C</li>
            <li>CSS 3</li>
            <li>Drupal</li>
            <li>Gimp</li>
            <li>git</li>
            <li>HTML 5</li>
            <li>Javascript</li>
            <li>jQuery</li>
            <li>Linux</li>
            <li>MariaDB</li>
            <li>MySQL</li>
            <li>PHP</li>
            <li>React</li>
            <li>Symfony</li>
            <li>WordPress</li>
         </ul>
      </div>
