<!-- WHAT DO WE DO -->

      <div class="paragraphs">
         <div class="title">
            Qué hacemos en OneDevs
         </div>
         <ul>
            <li>Asesoría y Consultoría Digital</li>
            <li>Ciberseguridad</li>
            <li>Contribución de Contenidos</li>
            <li>Desarrollo Apps Mobile</li>
            <li>Desarrollo Backend</li>
            <li>Desarrollo Frontend</li>
            <li>DevOps</li>
            <li>Diseño Gráfico</li>
            <li>E-Commerce</li>
            <li>Mantenimiento de Sites</li>
            <li>Maquetación</li>
            <li>Marketing On-Line</li>
            <li>SEO</li>
            <li>User eXperience</li>
            <li>User Interface</li>
         </ul>
      </div>

