<!-- CSS -->

<?php if ($GLOBALS['config']['environment'] === 'development') : ?>
      <link rel="stylesheet" href="/css/vars.css?v=<?= rnd_get_css_version() ?>" />
      <link rel="stylesheet" href="/css/fonts.css?v=<?= rnd_get_css_version() ?>" />
      <link rel="stylesheet" href="/css/page/home.css?v=<?= rnd_get_css_version() ?>" />
      <link rel="stylesheet" href="/css/component/brand.css?v=<?= rnd_get_css_version() ?>" />
      <link rel="stylesheet" href="/css/component/people.css?v=<?= rnd_get_css_version() ?>" />
      <link rel="stylesheet" href="/css/component/contact.css?v=<?= rnd_get_css_version() ?>" />
      <link rel="stylesheet" href="/css/component/address.css?v=<?= rnd_get_css_version() ?>" />
<?php else : ?>
      <link rel="stylesheet" href="/css/vars.css" />
      <link rel="stylesheet" href="/css/fonts.css" />
      <link rel="stylesheet" href="/css/page/home.css" />
      <link rel="stylesheet" href="/css/component/brand.css" />
      <link rel="stylesheet" href="/css/component/people.css" />
      <link rel="stylesheet" href="/css/component/contact.css" />
      <link rel="stylesheet" href="/css/component/address.css" />
<?php endif ?>
