<!-- ONEDEVS 404 PAGE -->

<!DOCTYPE html>

<html lang="es">

   <head>

      <title>__ OneDevs __ 404</title>
      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/head/metas.phtml'; ?>
      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/head/manifest.phtml'; ?>
      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/head/favicons.phtml'; ?>
      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/head/css/404.phtml'; ?>

   </head>

   <body>

      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/component/brand.phtml' ?>
      <?php echo_vertical_separator(50); ?>

      <div class="_404">
         404... 🤔
      </div>

   </body>

</html>
