<!-- ONEDEVS HOME PAGE -->

<!DOCTYPE html>

<html lang="es">

   <head>

      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/head/title.phtml'; ?>
      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/head/metas.phtml'; ?>
      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/head/manifest.phtml'; ?>
      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/head/favicons.phtml'; ?>
      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/head/css/home.phtml'; ?>

   </head>

   <body>

      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/component/brand.phtml' ?>

      <?php echo_vertical_separator(50, 0); ?>

      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/component/introduction.phtml'; ?>
      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/component/people.phtml'; ?>
      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/component/what-do-we-do.phtml'; ?>
      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/component/service-to.phtml'; ?>
      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/component/tech-stack.phtml'; ?>
      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/component/contact.phtml'; ?>
      <?php include_once $GLOBALS['config']['project_root_dir'] . '/phtml/component/address.phtml'; ?>

   </body>

</html>
