
      <!-- ADDRESS -->

      <div class="desktop">
         <div class="paragraphs-address">
            <p>
               <a target="_blank" href="https://www.google.com/search?q=onedevs+digital+services"><img src="/images/icons/social-networks/google.png" alt="Google" height="32" /></a> &nbsp;&nbsp;&nbsp;&nbsp;
               <a target="_blank" href="https://www.facebook.com/OneDevsDS"><img src="/images/icons/social-networks/facebook.png" alt="Facebook" height="32" /></a> &nbsp;&nbsp;&nbsp;&nbsp;
               <a target="_blank" href="https://www.instagram.com/onedevs"><img src="/images/icons/social-networks/instagram.png" alt="Instagram" height="32" /></a> &nbsp;&nbsp;&nbsp;&nbsp;
               <a target="_blank" href="https://www.linkedin.com/company/onedevs-digital-services"><img src="/images/icons/social-networks/linkedin.png" alt="LinkedIn" height="32" /></a> &nbsp;&nbsp;&nbsp;&nbsp;
               <a target="_blank" href="https://twitter.com/one_devs"><img src="/images/icons/social-networks/twitter.png" alt="Twitter" height="32" /></a> &nbsp;&nbsp;&nbsp;&nbsp;
               <a target="_blank" href="https://wa.me/34633823008"><img src="/images/icons/social-networks/whatsapp.png" alt="WhatsApp" height="32" /></a> &nbsp;&nbsp;
               <a target="_blank" href="https://www.google.com/maps/place/OneDevs+Digital+Services/@37.8796277,-4.7641025,15z/data=!4m5!3m4!1s0x0:0xd2ab458934f9329f!8m2!3d37.8796277!4d-4.7641025"><img src="/images/icons/google-maps-indicator-450x450.png" alt="Google Maps" height="32" /></a>
            </p>
         </div>
      </div>

      <div class="mobile">
         <div class="paragraphs-address">
            <p>
               <a target="_blank" href="https://www.google.com/search?q=onedevs+digital+services"><img src="/images/icons/social-networks/google.png" alt="Google" height="32" /></a> &nbsp;&nbsp;&nbsp;&nbsp;
               <a target="_blank" href="https://www.facebook.com/OneDevsDS"><img src="/images/icons/social-networks/facebook.png" alt="Facebook" height="32" /></a> &nbsp;&nbsp;&nbsp;&nbsp;
               <a target="_blank" href="https://www.instagram.com/onedevs"><img src="/images/icons/social-networks/instagram.png" alt="Instagram" height="32" /></a> &nbsp;&nbsp;&nbsp;&nbsp;
               <a target="_blank" href="https://www.linkedin.com/company/onedevs-digital-services"><img src="/images/icons/social-networks/linkedin.png" alt="LinkedIn" height="32" /></a> &nbsp;&nbsp;&nbsp;&nbsp;
            </p>
            <p>
               <a target="_blank" href="https://twitter.com/one_devs"><img src="/images/icons/social-networks/twitter.png" alt="Twitter" height="32" /></a> &nbsp;&nbsp;&nbsp;&nbsp;
               <a target="_blank" href="https://wa.me/34633823008"><img src="/images/icons/social-networks/whatsapp.png" alt="WhatsApp" height="32" /></a> &nbsp;&nbsp;
               <a target="_blank" href="https://www.google.com/maps/place/OneDevs+Digital+Services/@37.8796277,-4.7641025,15z/data=!4m5!3m4!1s0x0:0xd2ab458934f9329f!8m2!3d37.8796277!4d-4.7641025"><img src="/images/icons/google-maps-indicator-450x450.png" alt="Google Maps" height="32" /></a>
            </p>
         </div>
      </div>
