
      <!-- BRAND -->

      <div class="desktop">
         <div class="brand">
            <a href="/"><img class="company-logo" src="/images/logos/logo-onedevs-blanco-fondo-transparente-200x200.png" width="200" height="200" alt="OneDevs"></a>
            <div class="company-name"><a href="/">__ OneDevs __</a></div>
            <div class="company-motto"><a href="/">Developing The Future</a></div>
         </div>
      </div>

      <div class="mobile">
         <div class="brand">
            <a href="/"><img class="company-logo" src="/images/logos/logo-onedevs-blanco-fondo-transparente-125x125.png" width="125" height="125" alt="OneDevs"></a>
            <div class="company-name"><a href="/">__ OneDevs __</a></div>
            <div class="company-motto"><a href="/">Developing The Future</a></div>
         </div>
      </div>
