
      <!-- BRAND -->

      <div class="desktop">
         <div class="brand">
            <img class="company-logo" src="/images/logos/logo-onedevs-blanco-fondo-transparente-200x200.png" width="200" height="200" alt="OneDevs">
            <div class="company-name">__ OneDevs __</div>
            <div class="company-motto">Developing The Future</div>
         </div>
      </div>

      <div class="mobile">
         <div class="brand">
            <img class="company-logo" src="/images/logos/logo-onedevs-blanco-fondo-transparente-125x125.png" width="125" height="125" alt="OneDevs">
            <div class="company-name">__ OneDevs __</div>
            <div class="company-motto">Developing The Future</div>
         </div>
      </div>
