
      <!-- CONTACT -->

      <div class="paragraphs">

         <div class="desktop">
            <div class="title">
               ¿Quieres decirnos algo?
            </div>
         </div>

         <div class="mobile">
            <div class="title">
               Contáctanos
            </div>
         </div>

         <div class="form h-align-center">
            <form class="form-contact">
               <div class="field">
                  <input type="text" name="nombre" placeholder="Tu nombre *" class="w270 fs17px" />
               </div>
               <div class="field">
                  <input type="text" name="apellidos" placeholder="Tus apellidos" class="w270 fs17px" />
               </div>
               <div class="field">
                  <input type="text" name="empresa" placeholder="Nombre de tu empresa o negocio" class="w270 fs17px" />
               </div>
               <div class="field">
                  <input type="text" name="telefono" placeholder="Un teléfono de contacto *" class="w270 fs17px" />
               </div>
               <div class="field">
                  <input type="text" name="email" placeholder="Un email de contacto *" class="w270 fs17px" />
               </div>
               <div class="field">
                  <textarea name="mensaje" placeholder="Cuéntanos" class="w270 fs17px" rows="5"></textarea>
               </div>
               <div class="field send">
                  <div class="button clickable w250 fs17px js-contact-send">Enviar</div>
               </div>
            </form>
         </div>

      </div>
