
      <!-- CONTACT -->

      <div class="paragraphs">
         <div class="desktop">
            <div class="title">
               ¿Quieres decirnos algo?
            </div>
         </div>
         <div class="mobile">
            <div class="title">
               ¿Nos cuentas?
            </div>
         </div>
         <div class="desktop">
            <p>
               <br />
               <b>OneDevs Digital Services</b><br />
               <br />
               💻 <a target="_blank" href="mailto:onedevs.digital.services@gmail.com">onedevs.digital.services@gmail.com</a><br />
               🦜 <a target="_blank" href="tel:+34633823008">+34 633 823 008</a><br />
            </p>
         </div>
         <div class="mobile">
            <p>
               <br />
               <b>OneDevs Digital Services</b><br />
               <br />
               🦜 <a target="_blank" href="tel:+34633823008">+34 633 823 008</a><br />
            </p>
         </div>
      </div>
