
      <!-- COOKIES -->

      <div class="cookies">

         <div class="title">
            C O O K I E S
         </div>

         <div class="content">

            <p>
               Este sitio utiliza cookies para ofrecer una experiencia de navegación personalizada.
               Las cookies son pequeños archivos de texto que almacena y gestiona tu navegador. Son diferentes para cada usuario.
               Puedes aceptar o rechazar el uso de cookies por parte de onedevs.tech
            </p>

            <?php echo_vertical_separator(90) ?>


            <div class="form big-size">
               <input class="btn-aceptar-cookies w250" type="button" value="aceptar cookies" /><?php echo_horizontal_separator(60, 1); ?><input class="btn-rechazar-cookies w250" type="button" value="rechazar cookies" />
            </div>

         </div>

      </div>
