
      <!-- COOKIE CONSENT -->

      <div class="cookie-consent">

         <div class="title">
            C O O K I E S
         </div>

         <div class="content">

            <div class="desktop">
               <p>
                  <b>onedevs.tech</b> utiliza cookies propias y de terceros para ofrecer una experiencia de navegación mejorada.
                  Las cookies son pequeños trozos de información que tu navegador almacena y gestiona. Son diferentes para cada usuario.
                  Puedes aceptar o rechazar el uso que hacemos de tus cookies
               </p>

               <?php echo_vertical_separator(90) ?>


               <div class="form big-size">
                  <input class="btn-aceptar-cookies w250" type="button" value="aceptar cookies" /><?php echo_horizontal_separator(60, 1); ?><input class="btn-rechazar-cookies w250" type="button" value="rechazar cookies" />
               </div>

            </div>

            <div class="mobile">
               <p>
                  <b>onedevs.tech</b> utiliza cookies propias y de terceros para ofrecer una experiencia de navegación mejorada.
                  Puedes aceptar o rechazar el uso que hacemos de tus cookies
               </p>
               <div class="form big-size">
                  <input class="btn-aceptar-cookies w150" type="button" value="aceptar" /><?php echo_horizontal_separator(60, 1); ?><input class="btn-rechazar-cookies w150" type="button" value="rechazar" />
               </div>
            </div>

         </div>

      </div>
