
      <!-- FANS -->

      <div class="paragraphs">
         <div class="desktop">
            <div class="title">
               Somos fans de ... 🥰
            </div>
         </div>
         <div class="mobile">
            <div class="title">
               Fans de ... 🥰
            </div>
         </div>
         <p>
            <a target="_blank" href="https://es.wikipedia.org/wiki/Piensa_globalmente,_act%C3%BAa_localmente">"Think Global, Act Local"</a><br />
            <a target="_blank" href="https://es.wikipedia.org/wiki/Software_libre">Software Libre</a><br />
         </p>
      </div>
