
      <!-- INTRODUCTION -->

      <div class="desktop">

         <?php echo_vertical_separator(111, 0); ?>


      </div>         

      <div class="paragraphs">
         <div class="title">
            Digitalizamos tu negocio
         </div>
         <div class="desktop">
            <p>
               <ul>
                  <li>Diseñamos tu web y la ponemos en marcha</li>
                  <li>Montamos tu E-Commerce</li>
                  <li><br /></li>
                  <li><u>También:</u></li>
                  <li>Desarrollamos tu App Mobile</li>
                  <li>Hacemos Marketing Digital de tu empresa</li>
               </ul>
            </p>
         </div>
         <div class="mobile">
            <p>
               <ul>
                  <li>Diseñamos tu web</li>
                  <li>E-Commerce</li>
                  <li>Apps Mobile</li>
                  <li>Marketing Digital</li>
               </ul>
            </p>
         </div>
      </div>
