
      <!-- INTRODUCTION -->

      <div class="desktop">

         <?php echo_vertical_separator(111, 0); ?>


      </div>         

      <div class="paragraphs">

         <div class="desktop">

            <div class="title">
               Digitalizamos tu negocio
            </div>

            <p>
               <ul>
                  <li>Desarrollamos tu web y la ponemos en marcha</li>
                  <li>Montamos tu E-Commerce</li>
                  <li>Desarrollamos tu app mobile</li>
               </ul>
            </p>

         </div>

         <div class="mobile">

            <div class="title">
               Digitalizamos tu negocio
            </div>

            <p>
               <ul>
                  <li>Desarrollamos tu web</li>
                  <li>E-Commerce</li>
                  <li>Apps Mobile</li>
               </ul>
            </p>

         </div>

      </div>
