
      <!-- MENU -->

      <div class="menu">
         <table>
            <tbody>
               <tr>
                  <td class="options">
                     <div class="options d-none">
                        <ul class="options">
                           <li><a href="#introduction">Digitalizamos tu negocio</a></li>
                           <li><a href="#people">Somos #OneDevs</a></li>
                           <li><a href="#what-do-we-do">Qué hacemos</a></li>
                           <li><a href="#tech-stack">Tecnologías que usamos</a></li>
                           <li><a href="#contact">¿Quieres decirnos algo?</a></li>
                        </ul>
                     </div>
                  </td>
                  <td class="controls">
                     <div class="control open">
                        <img src="/images/icons/hamburger.png" alt="Menu Open" />
                     </div>
                     <div class="control close d-none">
                        <img src="/images/icons/times.png" alt="Menu Close" />
                     </div>
                  </td>
               </tr>
            </tbody>
         </table>
      </div>
