
      <!-- PEOPLE -->

      <div class="desktop">
         <div class="paragraphs">
            <div class="title">
               Somos #OneDevs
            </div>            
            <div class="collaborator">
               <table class="collaborator">
                  <tbody>
                     <tr>
                        <td class="image">
                           <img src="/images/people/richi.png" width="200" height="200" alt="Richi" />
                        </td>
                        <td class="content">
                           <span class="name-and-position">Ricardo Ruiz Martínez - CEO & PHP Developer</span><br />
                           <i>"Creamos OneDevs para poner nuestros conocimientos y experiencia al servicio de nuestros clientes. Hacemos nuestras las necesidades digitales de tu negocio."</i><br />
                           <br />
                           <a target="_blank" href="tel:633823008">633 823 008</a><br />
                           <?php echo_vertical_separator(9, 27); ?>
                           <a target="_blank" href="mailto:onedevs.digital.services@gmail.com">onedevs.digital.services@gmail.com</a><br />
                        </td>
                     </tr>
                  </tbody>
               </table>
            </div>
         </div>
      </div>

      <div class="mobile">
         <div class="paragraphs">
            <div class="title">
               Somos #OneDevs
            </div>            
            <div class="collaborators">
               <div class="collaborator">
                  <div class="image">
                     <img src="/images/people/richi.png" width="200" height="200" alt="Richi" />
                  </div>
                  <div class="content">
                     <span class="name-and-position">Ricardo Ruiz Martínez - CEO & PHP Developer</span><br />
                     <i>"Creamos OneDevs para poner nuestros conocimientos y experiencia al servicio de nuestros clientes. Hacemos nuestras las necesidades digitales de tu negocio."</i><br />
                     <br />
                     <a target="_blank" href="tel:633823008">633 823 008</a><br />
                     <a target="_blank" href="mailto:onedevs.digital.services@gmail.com">onedevs.digital.services@gmail.com</a><br />
                  </div>
               </div>
            </div>
         </div>
      </div>
