
      <!-- PEOPLE -->

      <div class="desktop">
         <div class="paragraphs">
            <div class="title">
               Somos #OneDevs
            </div>            
            <div class="collaborator">
               <table class="collaborator">
                  <tbody>
                     <tr>
                        <td class="image">
                           <img src="/images/people/richi.png" width="200" height="200" alt="Richi" />
                        </td>
                        <td class="content">
                           <a href="people/ricardo-ruiz-martinez"><b>Ricardo Ruiz Martínez - CEO & PHP Developer</b></a><br />
                           <i>"En OneDevs ponemos todos nuestros conocimientos y experiencia al servicio de nuestros clientes. Hacemos nuestras las necesidades digitales de tu negocio."</i><br />
                           <br />
                           <a target="_blank" href="https://wa.me/34633823008"><img align="absmiddle" src="/images/icons/whatsapp-w20.png" width="20" alt="WhatsApp" /></a> <a target="_blank" href="https://wa.me/34633823008">633 823 008</a><br />
                           <?php echo_vertical_separator(9, 27); ?>
                           <a target="_blank" href="mailto:info@onedevs.tech">info@onedevs.tech</a><br />
                        </td>
                     </tr>
                  </tbody>
               </table>
            </div>
         </div>
      </div>

      <div class="mobile">
         <div class="paragraphs">
            <div class="title">
               Somos #OneDevs
            </div>
            <div class="collaborators">
               <div class="collaborator">
                  <div class="image">
                     <img src="/images/people/richi.png" width="200" height="200" alt="Richi" />
                  </div>
                  <div class="content">
                     <a href="people/ricardo-ruiz-martinez"><b>Ricardo Ruiz Martínez - CEO & PHP Developer</b></a><br />
                     <i>"En OneDevs ponemos todos nuestros conocimientos y experiencia al servicio de nuestros clientes. Hacemos nuestras las necesidades digitales de tu negocio."</i><br />
                     <br />
                     <a target="_blank" href="https://wa.me/34633823008"><img align="absmiddle" src="/images/icons/whatsapp-w13.png" width="13" alt="WhatsApp" /></a> <a target="_blank" href="https://wa.me/34633823008">633 823 008</a><br />
                     <a target="_blank" href="mailto:info@onedevs.tech">info@onedevs.tech</a><br />
                  </div>
               </div>
            </div>
         </div>
      </div>
