<!-- TECH STACK -->

      <div class="paragraphs">
         <div class="title">
            Algunas tecnologías que usamos
         </div>
         <ul>
            <li>ASM 80x86</li>
            <li><a target="_blank" href="https://www.open-std.org/jtc1/sc22/wg14">C</a></li>
            <li><a target="_blank" href="https://www.w3.org/Style/CSS">CSS 3</a></li>
            <li><a target="_blank" href="https://www.drupal.org">Drupal</a></li>
            <li><a target="_blank" href="https://www.gimp.org">Gimp</a></li>
            <li><a target="_blank" href="https://git-scm.com">git</a></li>
            <li><a target="_blank" href="https://html.spec.whatwg.org/multipage">HTML 5</a></li>
            <li><a target="_blank" href="https://developer.mozilla.org/es/docs/Web/JavaScript">Javascript</a></li>
            <li><a target="_blank" href="https://jquery.com">jQuery</a></li>
            <li><a target="_blank" href="https://www.linux.org">Linux</a></li>
            <li><a target="_blank" href="https://mariadb.org">MariaDB</a></li>
            <li><a target="_blank" href="https://www.mysql.com">MySQL</a></li>
            <li><a target="_blank" href="https://www.php.net">PHP</a></li>
            <li><a target="_blank" href="https://symfony.com">Symfony</a></li>
            <li><a target="_blank" href="https://wordpress.com">WordPress</a></li>
         </ul>
      </div>

