
      <!-- TECH STACK -->

      <div class="paragraphs">

         <div class="desktop">
            <div class="title">
               Tecnologías que usamos
            </div>
         </div>

         <div class="mobile">
            <div class="title">
               Tecnologías
            </div>
         </div>

         <ul>

            <li class="section">Frameworks Backend</li>
               <li><a target="_blank" href="https://www.php.net">PHP plano</a></li>
               <li><a target="_blank" href="https://symfony.com">Symfony</a></li>

            <li class="section">Control de versiones</li>
               <li><a target="_blank" href="https://git-scm.com">git</a></li>

            <li class="section">Sistemas operativos & DevOps</li>
               <li><a target="_blank" href="https://www.linux.org">Linux</a></li>

            <li class="section">CMS</li>
               <li><a target="_blank" href="https://wordpress.com">WordPress</a></li>
               <li><a target="_blank" href="https://www.drupal.org">Drupal</a></li>

            <li class="section">Bases de datos</li>
               <li><a target="_blank" href="https://mariadb.org">MariaDB</a></li>
               <li><a target="_blank" href="https://www.mysql.com">MySQL</a></li>

            <li class="section">FrontEnd</li>
               <li><a target="_blank" href="https://html.spec.whatwg.org/multipage">HTML 5</a></li>
               <li><a target="_blank" href="https://www.w3.org/Style/CSS">CSS 3</a></li>
               <li><a target="_blank" href="https://jquery.com">jQuery</a></li>
               <li><a target="_blank" href="https://developer.mozilla.org/es/docs/Web/JavaScript">Javascript</a></li>

            <li class="section">Diseño gráfico</li>
               <li><a target="_blank" href="https://www.gimp.org">Gimp</a></li>
               <li><a target="_blank" href="https://www.libreoffice.org/discover/impress">Impress</a></li>

            <li class="section">Otras tecnologías</li>
               <li><a target="_blank" href="https://www.open-std.org/jtc1/sc22/wg14">C</a></li>
               <li><a target="_blank" href="https://en.wikipedia.org/wiki/X86_assembly_language">ASM 80x86</a></li>

         </ul>

      </div>
