<!-- WHAT DO WE DO -->

      <div class="paragraphs">
         <div class="desktop">
            <div class="title">
               Qué hacemos en OneDevs
            </div>
         </div>
         <div class="mobile">
            <div class="title">
               Qué hacemos
            </div>
         </div>
         <ul>
            <li>Asesoría y Consultoría Digital</li>
            <li>
               <u>Ciberseguridad:</u>
               <ul>
                  <li>Corrección de vulnerabilidades</li>
                  <li>Pentesting</li>
               </ul>
            </li>
            <li>Contribución de Contenidos</li>
            <li>
               <u>Desarrollo:</u>
               <ul>
                  <li>Apps Mobile</li>
                  <li>Bugfixing</li>
                  <li>Evolutivos & Mantenimiento Web</li>
                  <li>Backend PHP</li>
                  <li>Frontend Javascript</li>
               </ul>
            </li>
            <li>
               <u>DevOps:</u>
               <ul>
                  <li>Administración de sistemas Linux</li>
                  <li>Despliegue de aplicaciones PHP en producción</li>
                  <li>Linux CLI</li>
               </ul>
            </li>
            <li>Diseño Gráfico</li>
            <li>E-Commerce</li>
            <li>Maquetación</li>
            <li>Marketing Digital</li>
            <li>SEO</li>
            <li>User eXperience</li>
            <li>User Interface</li>
         </ul>
      </div>

