
      <!-- WHAT DO WE DO -->

      <div class="paragraphs">

         <div class="desktop">

            <div class="title">
               Qué hacemos
            </div>

            <ul>

               <li class="section">Web</li>
                  <li>Reservamos tu dominio en Internet</li>
                  <li>Alojamos tu web en nuestros servidores</li>

               <li class="section">Desarrollo</li>
                  <li>Diseñamos y desarrollamos tu web</li>
                  <li>Backend PHP</li>
                  <li>Mantenimiento de tu web & Evolutivos</li>
                  <li>Bugfixing</li>
                  <li>Maquetación</li>
                  <li>Frontend Javascript</li>
                  <li>Desarrollamos tu app mobile</li>

               <li class="section">DevOps</li>
                  <li>Administración de sistemas Linux</li>
                  <li>Despliegue de aplicaciones</li>
                  <li>Automatización de procesos</li>
                  <li>Administración de bases de datos MySQL</li>

               <li class="section">Ciberseguridad</li>
                  <li>Corrección de vulnerabilidades</li>
                  <li>Pentesting</li>

               <li class="section">También hacemos</li>
                  <li>Formación Digital</li>
                  <li>E-Commerce</li>
                  <li>Contribución de Contenidos</li>
                  <li>Asesoramiento en Digitalización</li>
                  <li>Diseño Gráfico</li>
                  <li>Presencia en Redes Sociales</li>
                  <li>UX / UI</li>
                  <li>Marketing Digital</li>
                  <li>SEO</li>

            </ul>

         </div>

         <div class="mobile">

            <div class="title">
               Qué hacemos
            </div>

            <ul>

               <li class="section">Web</li>
                  <li>Tu dominio en Internet</li>
                  <li>Hosting de tu web</li>

               <li class="section">Desarrollo</li>
                  <li>Desarrollamos tu web</li>
                  <li>Backend PHP</li>
                  <li>Mantenimiento</li>
                  <li>Evolutivos</li>
                  <li>Bugfixing</li>
                  <li>Maquetación</li>
                  <li>Frontend Javascript</li>
                  <li>Apps Mobile</li>

               <li class="section">DevOps</li>
                  <li>Administración Linux</li>
                  <li>Despliegues</li>
                  <li>Automatización Procesos</li>
                  <li>BB.DD. MySQL</li>

               <li class="section">Ciberseguridad</li>
                  <li>Fix Vulnerabilidades</li>
                  <li>Pentesting</li>

               <li class="section">También hacemos</li>
                  <li>Formación Digital</li>
                  <li>E-Commerce</li>
                  <li>Contribución</li>
                  <li>Asesoramiento</li>
                  <li>Diseño Gráfico</li>
                  <li>Presencia en RR.SS.</li>
                  <li>UX / UI</li>
                  <li>Marketing Digital</li>
                  <li>SEO</li>

            </ul>

         </div>

      </div>
