
      <!-- CSS -->

      <link rel="stylesheet" href="/css/vars.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/fonts.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/desktop-mobile.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/page/404.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/component/brand.css?v=<?= rnd_get_digits_string() ?>" />
