
      <!-- CSS -->

<?php if ($GLOBALS['config']['environment'] === 'development') : ?>
      <link rel="stylesheet" href="/css/vars.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/colors.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/fonts.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/width-height.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/align.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/font-size.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/clickable.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/d-none.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/desktop-mobile.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/form.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/page/home.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/component/brand.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/component/menu.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/component/people.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/component/address.css?v=<?= rnd_get_digits_string() ?>" />
      <?php if (\cookie_not_exists('OneDevsTechCookieConsent')) : ?><link rel="stylesheet" href="/css/component/cookie-consent.css?v=<?= rnd_get_digits_string() ?>" /><?php endif; ?>
<?php else : ?>
      <link rel="stylesheet" href="/css/vars.css" />
      <link rel="stylesheet" href="/css/colors.css" />
      <link rel="stylesheet" href="/css/fonts.css" />
      <link rel="stylesheet" href="/css/width-height.css" />
      <link rel="stylesheet" href="/css/align.css" />
      <link rel="stylesheet" href="/css/font-size.css" />
      <link rel="stylesheet" href="/css/clickable.css" />
      <link rel="stylesheet" href="/css/d-none.css" />
      <link rel="stylesheet" href="/css/desktop-mobile.css" />
      <link rel="stylesheet" href="/css/form.css" />
      <link rel="stylesheet" href="/css/page/home.css" />
      <link rel="stylesheet" href="/css/component/brand.css" />
      <link rel="stylesheet" href="/css/component/menu.css" />
      <link rel="stylesheet" href="/css/component/people.css" />
      <link rel="stylesheet" href="/css/component/address.css" />
      <?php if (\cookie_not_exists('OneDevsTechCookieConsent')) : ?><link rel="stylesheet" href="/css/component/cookie-consent.css" /><?php endif; ?>
<?php endif ?>
