
      <!-- CSS -->

      <link rel="stylesheet" href="/css/vars.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/colors.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/fonts.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/width-height.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/align.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/font-size.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/clickable.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/d-none.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/desktop-mobile.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/form.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/body-0.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/page/privacy-policy.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/component/brand.css?v=<?= rnd_get_digits_string() ?>" />
      <?php if (\cookie_not_exists('OneDevsTechCookieConsent')) : ?><link rel="stylesheet" href="/css/component/cookie-consent.css?v=<?= rnd_get_digits_string() ?>" /><?php endif; ?>
