<!-- CSS -->

<?php if ($GLOBALS['config']['environment'] === 'development') : ?>
      <link rel="stylesheet" href="/css/vars.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/fonts.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/desktop-mobile.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/width-height.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/d-none.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/form.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/page/home.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/component/brand.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/component/introduction.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/component/people.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/component/contact.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/component/address.css?v=<?= rnd_get_digits_string() ?>" />
      <link rel="stylesheet" href="/css/component/cookies.css?v=<?= rnd_get_digits_string() ?>" />
<?php else : ?>
      <link rel="stylesheet" href="/css/vars.css" />
      <link rel="stylesheet" href="/css/fonts.css" />
      <link rel="stylesheet" href="/css/desktop-mobile.css" />
      <link rel="stylesheet" href="/css/width-height.css" />
      <link rel="stylesheet" href="/css/d-none.css" />
      <link rel="stylesheet" href="/css/form.css" />
      <link rel="stylesheet" href="/css/page/home.css" />
      <link rel="stylesheet" href="/css/component/brand.css" />
      <link rel="stylesheet" href="/css/component/introduction.css" />
      <link rel="stylesheet" href="/css/component/people.css" />
      <link rel="stylesheet" href="/css/component/contact.css" />
      <link rel="stylesheet" href="/css/component/address.css" />
      <link rel="stylesheet" href="/css/component/cookies.css" />
<?php endif ?>
